version: '2'
services: 

  rabbitmq:
    image: rabbitmq:3.9.5-management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: on-failure
    labels:
      kompose.service.type: LoadBalancer